apiVersion: v1
kind: Namespace
metadata:
  name:  nginx
--- 
apiVersion: apps/v1
kind: Deployment 
metadata:
  namespace: nginx 
  name: nginx-deployment
  labels:
    app: nginx_haproxy
    important: "true" 
spec: 
  replicas: 3 #default 1 #this will be overwrite if have HPA ref to
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # at same time the maximum how many pod can create
      maxUnavailable: 1 # at same time the maxium how many pod is deleting
  selector: 
    matchLabels:
      app: nginx_haproxy
  template:
    metadata:
      labels: #label marker to identifier the deployment references
        app: nginx_haproxy
    spec:   
      containers:
          - image: busybox
            name:  my-alpin
            command: ["/bin/sh", "-c", "while true; do wget -q -O- http://nginx-service; done && sleep 3600"]
            ports:
              - containerPort: 8080
            resources:
              limits: 
                memory: 512Mi
                cpu: 128m
              requests: 
                memory: 512Mi
                cpu: 128m
            env:
              - name:  HELLO 
                value:  "HOW ARE YOU"