apiVersion: v1
kind: Namespace
metadata:
  name:  nginx
--- 
apiVersion: apps/v1
kind: Deployment 
metadata:
  namespace: nginx 
  name: nginx-deployment
  labels:
    app: nginx_haproxy
    important: "true" 
spec: 
  replicas: 6 #default 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # at same time the maximum how many pod can create
      maxUnavailable: 1 # at same time the maxium how many pod is deleting
  selector: 
    matchLabels:
      app: nginx_haproxy
  template:
    metadata:
      labels: #label marker to identifier the deployment references
        app: nginx_haproxy
    spec:   
      containers:
          - image: nginx:latest
            name:  my-alpin
            ports:
              - containerPort: 8080
            resources:
              limits: 
                memory: 512Mi
                cpu: 256m
              requests: 
                memory: 512Mi
                cpu: 256m
            env:
              - name:  HELLO 
                value:  "HOW ARE YOU"