apiVersion: v1 #version of API - current supporting
kind: Namespace # kind of resources
metadata: # describe information or data of resources
  name:  hihi
---
apiVersion: v1
kind: Pod 
metadata:
  namespace: hihi
  name: helloworld
  labels:
    app: backend 
    important: "true"
spec: 
  containers:
    - image:  nginx:latest
      name:  my-alpin
      ports:
        - containerPort: 8080
      resources:
        limits: 
          memory: 512Mi
          cpu: 256m
        requests: 
          memory: 512Mi
          cpu: 256m
      env:
        - name:  HELLO 
          value:  "HOW ARE YOU"


