apiVersion: v1
kind: Namespace
metadata:
  name:  nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx
  name: mongo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - mongo
              topologyKey: "kubernetes.io/hostname"
      # topologySpreadConstraints:
      #   - maxSkew: 2 # allow a maximum imbalance of 2 pod between zones
      #     topologyKey: "topology.kubernetes.io/region"
      #     whenUnsatisfiable: ScheduleAnyway
      #     labelSelector:
      #       matchLabels:
      #         app: mongo
      containers:
        - name: mongo
          image: mongo:latest
          resources: 
            requests: 
              cpu: 128m
              memory: 256Mi
            limits: 
              cpu: 128m
              memory: 256Mi
