apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx
  namespace: nginx
  labels:
    app:  nginx
spec:
  replicas: 4
  selector: 
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app:  nginx
    spec:
      containers:
      - image: quyencl91/appheathcheck:latest
        name: nginx
        resources:
          requests:
            cpu: "256m"
            memory: "512M"
          limits: 
            cpu: "256m"
            memory: "512M"
        ports:
        - containerPort: 8080
          name:  nginx
