apiVersion: v1
kind: Pod
metadata:
  name: pod-azure-disk
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: "/data"
      name: azure-volume
  volumes:
  - name: azure-volume
    azureDisk:
      diskName: "my-azure-disk"
      diskURI: "/subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.Compute/disks/my-azure-disk"