apiVersion: v1
kind: Pod
metadata:
  name: pod-emptydir
spec:
  containers:
  - name: container1
    image: nginx
    resources:
      requests: 
        cpu: 256m
        memory: 512Mi
      limits:
        cpu: 256m
        memory: 512Mi
    volumeMounts:
    - mountPath: "/cache"
      name: cache-volume
  - name: container2
    image: busybox
    resources:
      requests: 
        cpu: 256m
        memory: 512Mi
      limits:
        cpu: 256m
        memory: 512Mi
    command: ["sh", "-c", "echo Hello > /cache/test.txt && sleep 3600"]
    volumeMounts:
    - mountPath: "/cache"
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}