# PersistentVolume (PV)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rwo
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  hostPath:
    path: "/Users/nulled/OneDrive/Projects/VTI/demo/kuberentes/storages/tmp"
---
# PersistentVolumeClaim (PVC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rwo #ReadWriteOnce
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: default
---
# Pod using the PVC
apiVersion: v1
kind: Pod
metadata:
  name: pod-rwo
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: 256m
        memory: 512Mi
      limits:
        cpu: 256m
        memory: 512Mi
    volumeMounts:
    - mountPath: "/var/www"
      name: rwo-volume
  volumes:
  - name: rwo-volume
    persistentVolumeClaim:
      claimName: pvc-rwo