apiVersion: v1
kind: Secret
metadata:
  name: example-secret
type: Opaque
data:
  password: cGFzc3dvcmQ= # base64 encoded "password"

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: "/etc/secret"
      name: secret-volume
  volumes:
  - name: secret-volume
    secret:
      secretName: example-secret